# Generated by Django 4.2.7 on 2026-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
