# Generated by Django 4.2.7 on 2026-06-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_groupchat_groupmessage_groupmessageimage_groupinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
